--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/dktapps-pm-pl/pmforms-demo
build-by-default: true
branches:
- master
projects:
  pmforms-demo:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
...
